/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
__int64 sub_401020(); // weak
// DIR *opendir(const char *name);
// int printf(const char *format, ...);
// int closedir(DIR *dirp);
// int strcmp(const char *s1, const char *s2);
// struct dirent *readdir(DIR *dirp);
// int usleep(__useconds_t useconds);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void dl_relocate_static_pie();
char *deregister_tm_clones();
__int64 register_tm_clones(); // weak
char *_do_global_dtors_aux();
void __cdecl del(const char *dir, const char *name);
void __cdecl checkDir(const char *scan_dir, int delay, const char *search_name);
int __fastcall main(int argc, const char **argv, const char **envp);
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (*qword_404010)(void) = NULL; // weak
char _bss_start; // weak


//----- (0000000000401000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4040A8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000401020) ----------------------------------------------------
__int64 sub_401020()
{
  return qword_404010();
}
// 401020: using guessed type __int64 sub_401020();
// 404010: using guessed type __int64 (*qword_404010)(void);

//----- (0000000000401090) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (__fastcall *)(int, char **, char **))main, v4, &retaddr, 0LL, 0LL, a3, &v5);
  __halt();
}
// 40109A: positive sp value 8 has been found
// 4010A1: variable 'v3' is possibly undefined

//----- (00000000004010C0) ----------------------------------------------------
void dl_relocate_static_pie()
{
  ;
}

//----- (00000000004010D0) ----------------------------------------------------
char *deregister_tm_clones()
{
  return &_bss_start;
}
// 404058: using guessed type char _bss_start;

//----- (0000000000401100) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}
// 401100: using guessed type __int64 register_tm_clones();

//----- (0000000000401140) ----------------------------------------------------
char *_do_global_dtors_aux()
{
  char *result; // rax

  if ( !_bss_start )
  {
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 404058: using guessed type char _bss_start;

//----- (0000000000401172) ----------------------------------------------------
void __cdecl del(const char *dir, const char *name)
{
  printf("%s/%s\n", dir, name);
}

//----- (000000000040119F) ----------------------------------------------------
void __cdecl checkDir(const char *scan_dir, int delay, const char *search_name)
{
  struct dirent *dir; // [rsp+20h] [rbp-10h]
  DIR *d; // [rsp+28h] [rbp-8h]

  while ( 1 )
  {
    d = opendir(scan_dir);
    if ( !d )
      break;
    while ( 1 )
    {
      dir = readdir(d);
      if ( !dir )
        break;
      usleep(delay);
      if ( !strcmp(dir->d_name, search_name) )
        del(scan_dir, search_name);
    }
    closedir(d);
  }
}

//----- (000000000040122B) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  checkDir(".", 1501, "test1");
  return 0;
}

//----- (0000000000401258) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=26 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled

