
lab1:
	g++ \
		-fdiagnostics-color=always \
		-std=c++20 \
		-I include \
		src/DNF.cpp src/Impl.cpp \
		lab1.cpp \
		-o lab1

lab2:
	c++ \
		-Wall -Wextra -Werror \
		-fdiagnostics-color=always -std=c++2a \
		-I include \
		-O0 -g3 \
		-o lab2 \
		src/Table.cpp src/TableItem.cpp \
		lab2.cpp


.PHONY: lab1 lab2
